### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by DarrianCZE** [Fragtality/Fenix2GSX#10]
Hi!

Why can't you make a simple installer, which would save the hassle of editing the FSUIPC config, etc...?

Also, BTW, do you know that MSFS has an auto-start .exe functionality as well? This is not only related to the FSUIPC, and if you could make an installer which would add an entry there, it would extremely streamline the process.

https://forums.flightsimulator.com/t/start-multiple-programs-on-msfs-startup-with-this-exe-xml-tip/350698

**Comment by Fragtality** [comment]
Nobody is required to edit either the FSUIPC Config or the exe.xml for Fenix2GSX to work. It works just fine when started manually.

I do know that, but again: Autostart is not a Requirement and it is up to the User if and how the Tool is started automatically.
