### ISSUE TITLE
Feature Request: Ability to swap between ACP1 and ACP2 (for flying as F/O)

### ISSUE THREAD

**Issue by redbullracing5** [Fragtality/Fenix2GSX#14]
Hi there

I really love what Fenix2GSX does currently, its been great not needing the GSX menu anymore. What I absolutely love is the usage of the ACP in the plane, but as I fly from the right hand seat, it would be great if one could swap which ACP feeds the values into the program, if that is possible?

Thanks for this amazing piece of software. 👍 😄

**Comment by Fragtality** [comment]
Hi redbull,
thanks for the Feedback :)

It is not really planned to it configurable which ACP is used. It is somewhat assumed, that Pilots so concerned about their Seat-Position and minimizing Menu Interaction do not really Mouse-Click in their Cockpit. So all it takes would be changing the Binding of Key/Button. 
That was at least the initial Though-Process. Maybe (or maybe not) I change it in the Future.

**Comment by redbullracing5** [comment]
Hey Fragtality,

thanks for getting back to me on this one! Well, I am not sure its so uncommon to be concerned about on which site to sit and still click around in the cockpit. The reason I do this is because my joystick is righthanded, and my 2nd monitor for charts & efb is also on the right hand side, so it just fits better to sit on the right hand side, too. :)

Should this get implemented eventually I'd be very happy, but if not I can also survive this without issue I guess. :)

**Comment by Fragtality** [comment]
@redbullracing5 
Implemented in [RC8](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC8) - please Check if that is what you were looking for 😉

**Comment by Fragtality** [comment]
Closed, implemented
