### ISSUE TITLE
GSX not respecting "Disable Crew De-/Boarding" option

### ISSUE THREAD

**Issue by Terminal-Rat** [Fragtality/Fenix2GSX#15]
Hi, me again.

GSX continues to pop up and ask if I want to deboard crew even with the disable crew deboarding option selected. The Fenix2GSX log shows "Crew boarding disabled". This only happens during deboarding, as far as I can tell. Boarding works as expected.

**Comment by Fragtality** [comment]
On a parking with/without Jetway? Or does that happen in either Case?

**Comment by Terminal-Rat** [comment]
It happens at both, as far as I can tell. Let me see if I have a full log file from my last flight.

**Comment by Fragtality** [comment]
You don't need to disable VHF1 - just set the Loglevel back to "Debug" in the Fenix2GSX.dll.config

**Comment by Fragtality** [comment]
When do you generated the new SimBrief Flightplan and when did you import it in the EFB?
(Before / While / After Deboarding)

**Comment by Terminal-Rat** [comment]
When I generate it changes, sometimes it's in air to prep for a short turn, sometimes it'll be afterwards. I don't have a specific procedure. If I do deboard, I import after deboarding is complete.

**Comment by Fragtality** [comment]
So it also happens when you generate the new Simbrief FP after Deboarding?

**Comment by Fragtality** [comment]
@Terminal-Rat 
Try if [RC8](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC8) solves the Issue. Seems I had set to many L-Vars^^

**Comment by Fragtality** [comment]
@Terminal-Rat 
Ok, try [RC15](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC15) - I think now I finally got it 🤣

**Comment by Fragtality** [comment]
Closed since no Feedback was received
