### ISSUE TITLE
[Feature Request] Option to disable auto-minimize

### ISSUE THREAD

**Issue by christophjurczyk** [Fragtality/Fenix2GSX#16]
Hi,
First of all very thanks for this nice tool. It really gain a lot the flight experience.

Normally, I have the app on a screen in the foreground to monitor the app. Unfortunately, the auto-minimize at startup forces me to get the app via the taskbar. An option to disable the auto-minimize at startup would be nice.

-Christoph

**Comment by Fragtality** [comment]
Hello Christoph,
thanks for your Feedback!

Well, there is no auto-minimize Functionality at all, the App does not create a Window unless the User clicks on the Systray/Notification Icon. So there is nothing to disable. The whole Goal is to have less "App-Interaction", so it is not intended to have the GUI all the Time open for Monitoring.
I'd rather be interested why you feel the Need to monitor it, that is not the intended way of using it.

**Comment by christophjurczyk** [comment]
Indeed, you're right the time which I am monitoring the tool is getting more and more less. Sometimes I am not sure if it triggered right (e.g. today after boarding the loadsheet transmission), but otherwise it's not required. So you are right seems not really a required feature. I will try to keep the tool minimized. :)
