### ISSUE TITLE
After receiving final load sheet, everything got reset

### ISSUE THREAD

**Issue by fresH229a** [Fragtality/Fenix2GSX#17]
Hey,

this happens now 3 times.
The Boarding process and everything is going well, but after receiveing the final load sheet, disconnecting the Jetway:

- The Chocks and GPU gets reconnected
- Fuel and load will be reset to default (3000 / 0 Pax / 0 Cargo)
- The Simbrief flight which has been loaded prior the flight is also deleted

Is this a known error or is there something I am doing wrong now.
It works fine with prior versions.

BR

**Comment by Fragtality** [comment]
Logs?
Steps?
Which was the Version where this started to happen?

**Comment by fresH229a** [comment]
Steps to reproduce:

- Start APU during final Boarding phase
- Beacon on after boarding finished
- APU avail, EXT Pwr Button pressed and than the plugin starts to disconnect the Ground Stuff and the Jetway.
Here the reset happend.
[Fenix2GSX20230617.log](https://github.com/Fragtality/Fenix2GSX/files/11781121/Fenix2GSX20230617.log)
[Fenix2GSX20230618.log](https://github.com/Fragtality/Fenix2GSX/files/11781122/Fenix2GSX20230618.log)

Which logs do you need? The debug log file?
[debug.log](https://github.com/Fragtality/Fenix2GSX/files/11781120/debug.log)

**Comment by Fragtality** [comment]
How is you EFB Setup/Usage in Detail?
Somehow the Flightplan seemed to have been resetted. The Tool got an ID of "0" reported and then the original ID again. So the Reset came very likely through Fenix. I don't reset the Mass & Balance on a new Flightplan ID. The only change to M&B outside of De/Boarding & Refueling is when Refueling is called an the current Fuel is greater the planned Fuel.

**Comment by fresH229a** [comment]
I just load the Flight with the EFB, nothing more :(
With the internal, probably I should try it with the external on my Tablet again.

**Comment by Fragtality** [comment]
No further Feedback, could not be observed on Test-Flights => Closed
