### ISSUE TITLE
Refueling ECAM memo

### ISSUE THREAD

**Issue by wody** [Fragtality/Fenix2GSX#2]
First of all that you very much for your fantastic work with all your tools. Really a great addition and immersion bringer! :-)

Using all auto Options in Fenix2GSX I get no "Refueling" ECAM indication, even though the refueling itself is working fine and correct.
Is that something wrong eventually on my side, or the same behavior for you as well?

**Comment by Fragtality** [comment]
Thanks! Glad you like it :)

It is normal that you don't see that ECAM Message. Did not really investigate how that Message is triggered ^^
But I'll look into it again - was initially more focused on if and how I can get the basic Stuff working ;)

**Comment by wody** [comment]
Great, yes that's a minor thing, was just wondering if I missed something :)
Thanks a lot!

**Comment by Fragtality** [comment]
Found it, will come in the next Version ;)

Since you've infected me with the ECAM-Fever, I'm currently exploring if the "NW STRG DISC" Message can also be synched better 😅

**Comment by wody** [comment]
Hehe :-D Thats great to hear. Thanks for looking into it that quickly.

Do you have a buymeacoffee link or something? ;-)

**Comment by Fragtality** [comment]
Nope. But I would not say no to a Rating when I make it available on flightsim.to so People know there is a Solution ;D

**Comment by Fragtality** [comment]
The Nw Strg Disc Message won't make it, the GSX Variable for the ByPass Pin is not implemented / not working :/

**Comment by wody** [comment]
What a pitty - but thanks a lot for looking into it :-)

**Comment by Fragtality** [comment]
ECAM Message available with 0.2.8 :wink:

**Comment by wody** [comment]
Nice thanks :-) Working great for me as well.

**Comment by Fragtality** [comment]
Well then: Case closed! :joy:
