### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by ecortinas** [Fragtality/Fenix2GSX#20]
There is an odd issue with the scaling of the window. I think it has to do with my windows settings having the font at 125% and not 100%.

![Screenshot 2023-07-07 173329](https://github.com/Fragtality/Fenix2GSX/assets/88294949/5abf54f8-cce5-4746-b088-988a80ae756d)

**Comment by Fragtality** [comment]
Hmm, it is not 125% Scaling alone - I do have that configured too. What is your Resolution?

**Comment by ecortinas** [comment]
2560x1440

**Comment by Fragtality** [comment]
That is also exactly my Resolution ^^

**Comment by ecortinas** [comment]
So my scanning is 100%, but I adjusted the windows text size in accessibility to 125%.

So it's possible that because the screen size didn't readjust and only text size did it clipped

**Comment by Fragtality** [comment]
Ah ok, that Scaling/Setting!

Did not say it is impossible, just trying to figure out the Conditions ;)
