### ISSUE TITLE
Fenix EFB departure countdown broken

### ISSUE THREAD

**Issue by mebourne** [Fragtality/Fenix2GSX#21]
Hi, thanks so much for this great program.

It appears that somehow it breaks the departure countdown on the EFB first page, without fenix2gsx it tells me how long until STD and then correctly sets ATD with pushback.

With fenix2gsx immediately it says Departing in blue and has already filled in the ATD with current time.

As a consequence this also breaks the Fenix company message system which nags you when late and asks for the delay allocation. I really miss that so hopefully you can fix it. Cheers!

**Comment by mebourne** [comment]
OK thanks. That's a bit disappointing but fully understandable given it's a freeware tool.

**Comment by mebourne** [comment]
I've found out what's causing this early departure. It's not your app but the interaction with GSX and Fenix with the"reposition" function. Apparently moving the plane a few feet is enough for Fenix to decide that you are departing. I think it's probably on Fenix to fix this, they should probably check that at least the power is on, I've no idea if they'll care about GSX though.

Turning off the auto reposition in the Fenix 2GSX settings is a workaround for now.

**Comment by Fragtality** [comment]
I've added a Note to the Readme, thanks for Reporting 😃

**Comment by Fragtality** [comment]
@mebourne 
Try [RC14](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC14) and if it now works for you 😃

**Comment by mebourne** [comment]
Yes that's working now, thanks for fixing this.
