### ISSUE TITLE
Not Connecting with MF WASM 0.7.0

### ISSUE THREAD

**Issue by BrunchFS** [Fragtality/Fenix2GSX#22]
I have found this issue: 
When I open the Fenix2GSX.exe it does not connect with the sim only the first (MSFS) is green, the oders stay in red and at the Log Messages it says: Exception recived: (Exception 31)
I have followed all the instalation steps.

**Comment by peteauau** [comment]
same here

**Comment by Fragtality** [comment]
@peteauau
If you could tell what exactly you mean with "module", then it might BrunchFS too 😃 

@BrunchFS 
And you run everything (Fenix2GSX, MSFS, Fenix, GSX) under the same User / Elevation? Tried rebooting the Computer (after .NET was installed)?
If you know where the Logs end even looked into them, you could also share them 😉

**Comment by peteauau** [comment]
I  downloaded  the  mobilflight-wasm-module-0.7.0 which  was  the  wrong  one

**Comment by Fragtality** [comment]
Oh... thanks for your contributions, did not really know that there is a new Version of the MobiFlight WASM Module. 
On the first Glance only a new Command was added, so it should theoretically work - I'll have to investigate that!

**Comment by Fragtality** [comment]
Possibly User-Error due to the confusing source-only Release of Version 0.7.0
No Issues seen with 0.7.1 (which is the latest compiled Release)
