### ISSUE TITLE
Cargo set to 0 in the EFB, while passenger numbers and fuel quantities work perfectly

### ISSUE THREAD

**Issue by Jamxman** [Fragtality/Fenix2GSX#25]
Upon importing a flight into the EFB, both passenger numbers and fuel quantity work perfectly. However in the EFB, the cargo quantity is set to 0, even though in the flight plan there is a quantity of cargo stated. All animations work perfectly, including loading the cargo. Anyone else having this issue?

**Comment by Jamxman** [comment]
Seems to be happening every time with my easyJet 320 but with other airlines it doesn't seem to occur. Any reason why?

**Comment by Fragtality** [comment]
Why should be that an Issue of my Tool, when the Fenix EFB itself does only show 0 for Cargo? I only take what the EFB knows.

Theories:
- The Livery has an Issue and does something Strange in the Direction of Weight & Balance (if that is possible at all? don't know)
- Your SimBrief Profile for that Livery/Registration has an Issue

**Comment by Jamxman** [comment]
Thanks for the help, issue resolved. It was a SimBrief profile issue
