### ISSUE TITLE
how to update? Fenix pax do not show up on EFB

### ISSUE THREAD

**Issue by ashun99** [Fragtality/Fenix2GSX#28]

**Comment by ashun99** [comment]
Sorry about sending without message.
Two questions.
i see that there is un update today. how do i update Fenix2GSX?

With new fenix update, when i use fenix2gsx, fuel and cargo loading happens perfectly. When passengers start to load, i see them with gsx and also in simulator. However, the pax number does not change in fenix EFB. it remains 0. it wold impact on final loadsheet.

**Comment by Fragtality** [comment]
Uhm, just download the Release that is marked as "Latest" oO
https://github.com/Fragtality/Fenix2GSX/releases
Delete all the old Files & Folders and extract the new Version.

Boarding works fine, no Issue seen or reported (if RC7 or higher is used). Need Logs for that (in the Folder of the Binary, Fenix2GSX\<DATE>.log)

**Comment by Fragtality** [comment]
Considered answered because of no further Feedback

**Comment by ashun99** [comment]
Hi, sorry for late reply, away on holidays.
Yes, pax and loading works seamless.
About deleting old files and folders, where so they sit? I download new version in download folder and run the app file  form there. But where does that old version app folder/file sit?
Is there  any step by step guideline?

Thanks

**Comment by Fragtality** [comment]
Uhm well, the Folder of Fenix2GSX is there where you have put it?! It is an Zip-Archive, I can't possibly know where you have extracted it to.
Also you have already answered that Question yourself 😉 (I hope you mean you download, *extract* it and the run it from there. I can't guarantee it can work properly when it is directly run out of Archive aka Windows-Zip-Folder)

Nope there is no such Guideline and will not be, I can't write a Course about basic Windows/PC Usage.
