### ISSUE TITLE
Issue with startup

### ISSUE THREAD

**Issue by Berzerker** [Fragtality/Fenix2GSX#3]
Hello, I'm trying out this app, have verified I have the .NET runtimes, WASM module and GSX Pro installed, but am getting the following error when it tries to start up

![image](https://user-images.githubusercontent.com/448708/233403256-a07f90cf-fb68-49b5-89a8-4f80052f89fc.png)

Also noticed this error in the debug.log

> [0420/105200.414:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.

Any pointers?

**Comment by Berzerker** [comment]
I tried both manually and using the FSUIPC method of the `[Programs]` block.

I didn't try running as admin, would that have been necessary?

**Comment by Fragtality** [comment]
Very strange indeed.
Running it through FSUIPC does work very well for me and definitively when started manually.

Some of the strangest Errors I have seen is because People run Stuff as Admin. It is not required for any of my Tools to be run as admin.
So MSFS is therefore also started regularly?

**Comment by Berzerker** [comment]
> So MSFS is therefore also started regularly?
I don’t to anything special with regard to starting MSFS, just through Steam

> Did you change any of the Settings by Chance? If yes: which to what? In the GUI or the config File?
The only setting I changed was to disable calling Catering, in the GUI.

**Comment by Berzerker** [comment]
Sounds like the VHF app is indeed the problem, I didn't have vPilot open, if I open it before the app launches, then it all starts up fine.

**Comment by Fragtality** [comment]
Ahhh okay!!! 😃 

Then use that Workaround a little longer (hours / 1-2 Days). I'm currently finishing and testing the new Version 0.2.8 which improves the whole Audio Controlling! I'll specifically test if these Changes have fixed that Bug of course 😉

**Comment by Berzerker** [comment]
No worries at all.

I did also have an issue where the door didn't close (I have auto door simulation disable) when boarding/fueling was completed. I verified the parking brake and beacon were both on as well, and GPU disconnected (from overhead). Anything else I missed?

**Comment by Fragtality** [comment]
Hmm hard to tell like that. 
Since Asobo decided to add some own automatic Door-Handling-Code with SU12 - which does not help anybody but annoys everybody - it could be just a MSFS Glitch.
The only Situation I could think of is that you don't have waited for the Final Loadsheet? Only after that LS was triggered, the Tool will react on Ext Pwr+Beacon+Brake to remove the Ground-Equipment and Close the Door.
Or maybe it even was not triggered at all - it will only be triggered if Refueling and Boarding are recognized as finished.

Do you still have the Log from that Situation?

**Comment by Berzerker** [comment]
Boarding and fueling were both finished, and I believe I got the loadsheet before flicking the switches.

The log isn't very interesting:

```
2023-04-20 13:19:15.657 [INF] [ GsxController:RunServices        ] Boarding completed 
2023-04-20 13:19:16.772 [INF] [ GsxController:RunServices        ] Sending Final Loadsheet in 117s 
2023-04-20 13:20:47.424 [INF] [ GsxController:RunServices        ] APU Bleed enabled - removing PCA 
2023-04-20 13:21:26.100 [INF] [ GsxController:RunServices        ] Sending Final Loadsheet 
2023-04-20 13:21:51.619 [INF] [ GsxController:RunServices        ] Preparing for Pushback - removing Equipment 
2023-04-20 13:21:51.793 [INF] [ GsxController:RunServices        ] Removing Jetway 
2023-04-20 13:21:52.888 [INF] [ GsxController:RunServices        ] State Change: Depature -> Taxi-Out 
2023-04-20 13:33:51.117 [INF] [ GsxController:RunServices        ] State Change: Taxi-Out -> Flight 
2023-04-20 15:52:58.172 [INF] [ GsxController:RunServices        ] State Change: Flight -> Taxi-In (Waiting for Engines stopped and Beacon off)
```

**Comment by Fragtality** [comment]
Well in that Case, yes ^^ The Log shows the normal Process as it should be.
At "Sending Final Loadsheet" the Tool commands to close the Door (no toggle Command, so it will close or stays closed).

Do you have the Auto-Jetway Simulation also disabled?
And you're 100% sure that it did not close at all? Or could it be that you did not see it close and then triggered to open again by something else maybe?

Does that happen every time everywhere? Or in which Situations does that happen?

**Comment by Fragtality** [comment]
Version 0.2.8 is now available - please check if it works without Workaround now! :)

**Comment by Berzerker** [comment]
Just tried and yep it seems to work fine now! Thank you.

**Comment by Fragtality** [comment]
Nice!
Another Case closed :)
