### ISSUE TITLE
Request: Delay before automatic jetway/stair operation

### ISSUE THREAD

**Issue by piedmonitor** [Fragtality/Fenix2GSX#30]
Could a delay option please be added with the automatic jetway/stair operation functionality the way there is a delay field on repositioning?

I leave automatic repositioning off because sometimes I want to do it, sometimes I don't want to do it, so it'd be nice if I could add in a 10-15 second delay for the automatic jetway/stairs functionality so I can load in, move if I want to, and have them be connected, vs loading in and having them be connected before I move and potentially messing up the connection.

Thanks!

**Comment by Fragtality** [comment]
Try [RC14](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.1-RC14) 😉
