### ISSUE TITLE
Issue with connection... Exception received: (Exception: 31)

### ISSUE THREAD

**Issue by Surfusa27** [Fragtality/Fenix2GSX#31]
I reinstalled the current version of WASM multiple times and am running the correct net runtime but every time I open sim it only connects to MSFS (goes green) and everything else remains red. Followed is a series of log messages reading 
Connection not established - waiting 30s for retry
Exception received: (Exception: 31)
Exception received: (Exception: 31)
Exception received: (Exception: 31)
Under SimConnect Inspector it reads:
SetClientData.........
EXCEPTION_OUT_OF_BOUNDS

**Comment by Fragtality** [comment]
Well, the Logs would helpful, don't you think? (Fenix2GSX\<date>.log)

What happens if you start Fenix2GSX in the Main Menu?

**Comment by Surfusa27** [comment]
Sorry about that, I'm honestly not a very computer savvy guy and all this is new to me. Your software is super vital to my operation though and so I'm super passionate and appreciative about getting it working for me. 

It does the same thing when started from MFS2020 menu screen and that is what situation these logs are recorded in.
<img width="292" alt="Screenshot 2023-08-18 164740" src="https://github.com/Fragtality/Fenix2GSX/assets/142555920/9f71abc1-013d-4b9c-bfc8-db07e6dfec54">
<img width="382" alt="Screenshot 2023-08-18 164756" src="https://github.com/Fragtality/Fenix2GSX/assets/142555920/2ae3ebf8-80a2-47d8-9936-a30b4ea55ca7">

**Comment by Surfusa27** [comment]
Here is the log file as well:
[Fenix2GSX20230818.log](https://github.com/Fragtality/Fenix2GSX/files/12384509/Fenix2GSX20230818.log)

**Comment by Surfusa27** [comment]
Reading the log I now understand it may have something to do with the WASM module. Did I install it wrong?

**Comment by Fragtality** [comment]
Yep, very likely.
Fenix2GSX established a SimConnect Connection but can't establish an Exchange with the Module.

Well, it is like any other Module/Scenery/Plane - put it in the Community Folder.
Maybe you downloaded the 0.7.0 Version? It is confusingly a Source-Only Release. So even when put correctly in the Community Folder, it won't do anything.

**Comment by Surfusa27** [comment]
It looks like I have the 0.7.1 version of the mobiflight-event-module downloaded and extracted in my community folder already and I have reinstalled it multiple times to no avail.

**Comment by Fragtality** [comment]
Maybe the Application/Procedure you are using for Extraction creates an unwanted Subdirectory? It should be like
Community\mobiflight-event-module\layout.json

**Comment by Fragtality** [comment]
Considered answered due to no further Feedback
