### ISSUE TITLE
How to set up TS3 for audio control?

### ISSUE THREAD

**Issue by Frenkii** [Fragtality/Fenix2GSX#33]
Hey,
as always, great app!

How am I able to set up TeamSpeak 3 volume to, i.e. VHF3?

I tried the following, but nothing worked:
- VHF3=TeamSpeak 3
- VHF3=TeamSpeak3
- VHF3=TeamSpeak 3 Client
- VHF3=ts3client_win64

Thank you in advance

**Comment by Fragtality** [comment]
But the Rest of the Volume-Control works normally, yes?

You need to use the exact Name of the Binary (without .exe). That means the Name is Case-Sensitive!

Depending how TS3 works, it may be that it generally can't be controlled? Fenix2GSX assumes that an Application is active on only *one* Output-Device.

**Comment by Fragtality** [comment]
Considered answered due to no further Feedback
