### ISSUE TITLE
Wrong Final Loadsheet

### ISSUE THREAD

**Issue by deepdiver70** [Fragtality/Fenix2GSX#34]
Hi there! My final loadsheet always shows wrong figures. Also, how can I start the loading of the aircraft if I may not use "Load Aircraft"?

**Comment by Fragtality** [comment]
What exactly means showing the wrong figures? Wrong in comparison to?

**Comment by piedmonitor** [comment]
I think what they mean is something I noticed last night with RC15, I did not get the initial loadsheet sent until after refueling and boarding were completed, and then I got the final loadsheet a few minutes after that. It seemed like the initial loadsheet was the one that got delayed and not the final one.

**Comment by Fragtality** [comment]
Oh that is currently on my Radar! I assume it has something to do with the Fix to the ADC System.

It is fine to press "Resend Loadsheet" in the EFB to get the initial Loadsheet on the first Leg.

**Comment by Fragtality** [comment]
Was trying to reproduce it yesterday and it worked. Thought "screw this, I go flying" and it directly happened -.-

From which Device/Browser are you both using the EFB? When do you open it?
(Its one Difference that come to my Mind - I tested with using the EFB in the VC. But when flying I have it on my Tablet and opening the Page before I hit read to fly)

**Comment by piedmonitor** [comment]
I've just been using the in-sim EFB, have not been accessing it through an external device or browser.

**Comment by Fragtality** [comment]
Closed, since no Response was received by the OP

**Comment by deepdiver70** [comment]
Hi, I apologize for the late response. Also, I am aware now that it was a user error, so sorry for wasting your time. I didn’t catch the „changing values on the W&B page can brake it“ when I first read through the description. So because I always change the figures while it’s loading, that was probably why I got inaccurate figures.
