### ISSUE TITLE
how to delete previous version?

### ISSUE THREAD

**Issue by ashun99** [Fragtality/Fenix2GSX#35]
Hi, sorry for late reply, away on holidays.

About deleting old files and folders, where do they sit? I download new version in download folder and run the app file from there. But where does that old version app folder/file sit?
Is there any step by step guideline?
How do i know that the most recent version is running? Does it show version label anyehere?

Thanks

**Comment by Fragtality** [comment]
The same Way all other Files and Folder can be deleted on a Windows PC
https://github.com/Fragtality/Fenix2GSX/issues/28#issuecomment-1686222471
