### ISSUE TITLE
Fenix2GSX not calling Fuel/Catering on EFB FP Load

### ISSUE THREAD

**Issue by Airbumps** [Fragtality/Fenix2GSX#36]
Hey mate, using RC18 I'm not getting an automatic triggering of fuel or catering on loading the FP into the EFB.

https://imgur.com/aNMIgvy

its obviously detecting the FP, but it doesn't end up calling any services. GSX is loaded and all functions are working up until this point (re-positioning etc).

**Comment by Fragtality** [comment]
Logs?

**Comment by Airbumps** [comment]
[Fenix2GSX20230825.log](https://github.com/Fragtality/Fenix2GSX/files/12434503/Fenix2GSX20230825.log)

Odd - It says COUTL not running  but I'm sure it was as I was able to open the GSX menu and call the services manually... I wouldn't have posted anything but this occurred on three consecutive flights after I updated from RC15 to RC18 so figured maybe it was something in the new version.

**Comment by Airbumps** [comment]
Yep - Reloaded the sim and it was all good - Delete reference to this thread - must have been something on my end.

**Comment by Airbumps** [comment]
Hmmm, maybe that was it - I was at EGLL (which as you know is awash with simobjects) when it occured.

**Comment by Fragtality** [comment]
Also keep in Mind, that when using GSX and or AIG they have Options to spawn Service-Vehicles on the Ground (so even more SimObjects)!
