### ISSUE TITLE
Issues with Jetway

### ISSUE THREAD

**Issue by Alexr03** [Fragtality/Fenix2GSX#37]
Heya! Im having issues with the jetways --
When I spawn in to start the flight, I start up GSX Couatl (As I don't have it auto starting), when Fenix2GSX recognises its started, it repositions the aircraft then calls the jetway, then I go through the regular service flow. 

I import the flightplan in the EFB and catering and fuel truck comes and goes as per normal, after the 90s boarding is automatically requested by Fenix2GSX. At this point the jetway moves away from the aircraft (the rear staircase remains) and one of two things happen, either passengers start walking on air from the end of the jetway to the door of the aircraft or no passengers come at all and the aircraft is stuck with 10 PAX (I then have to set the "Load PAX" manually in the MCDU to fill the remaining passengers).

Similar thing happens when deboarding, I get to the gate, the jetway attaches, when deboarding starts the jetway detaches and passengers all walk on air to the gate.
I haven't encountered this situation when parking on a ramp where only stairs attach to the aircraft, it will remain attached throughout the deboarding cycle and passengers make it down the stairs into the bus just fine. It only seems to be at gates with a jetway.

Log:
[Fenix2GSX20230828_001.log](https://github.com/Fragtality/Fenix2GSX/files/12456430/Fenix2GSX20230828_001.log)

Settings:
![Fenix2GSX_dd68f7b3-d6c4-4bef-903a-8cd652d83434](https://github.com/Fragtality/Fenix2GSX/assets/11258483/010323df-7c68-4ff7-bd77-d5af374a4410)
![Couatl64_MSFS_2e7fe989-b028-4518-b6c0-0b731acc42d8](https://github.com/Fragtality/Fenix2GSX/assets/11258483/8919ba7c-3bef-444c-b458-2ac595efe2dc)
![Couatl64_MSFS_01cff461-277f-4486-b56f-b11a66a4dbe5](https://github.com/Fragtality/Fenix2GSX/assets/11258483/2221390d-3ad5-44f3-82a9-cb9f46df9686)

**Comment by Fragtality** [comment]
GSX is suppose to auto-start, what happens if you run it like intended?
Also try to disable GSX Audio-Control.

If it still persists enable debugJetways in the .config File and send me Log of a Session where it happened.

Since File-Name of the Log seems strange, it could also be an Issue how you start Fenix2GSX (and under which User you do that)

**Comment by Alexr03** [comment]
Apologies --
Disabling "Estimate passengers number" inside of GSX settings fixed the issue for me.
