### ISSUE TITLE
Check for updates on application startup

### ISSUE THREAD

**Issue by lediszep** [Fragtality/Fenix2GSX#38]
Thanks for the work you put into this fantastic addon, it works great!

As the title suggests, would it be possible for the application to check for updates on launch and possibly auto update? As there are quite a few releases and improvements constantly.

**Comment by Fragtality** [comment]
FYI, the Mods of the inofficial GSX Discord and I setup a Webhook, so the Information of new Releases is released there. (There is also a dedicated Channel for Fenix2GSX)

But yeah, at least a Notification would helpful indeed.
But an Auto Update just for Fenix2GSX - no. I'd rather Invest the Time to create a common Installer/Updater for all my Tools. The Time is just a Problem though ^^

**Comment by lediszep** [comment]
Ah yes, a common Installer/Updater would be very nice. Awesome thanks!

**Comment by Fragtality** [comment]
@lediszep @semartinezmo

Implemented with Version [0.3.2](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.2) !
