### ISSUE TITLE
Trigger to initiate deboarding

### ISSUE THREAD

**Issue by Arsedi** [Fragtality/Fenix2GSX#39]
Good evening,

A few days ago, I downloaded your program, and it works very well! Thank you very much for your excellent work.

I would like to make a suggestion if possible. For passenger deboarding, it would be better if the trigger were the seatbelt, as is done in real-life aircraft Standard Operating Procedures (SOPs). During parking, once the pilot shuts down the two engines, they wait for the engines to spool down and turn off the beacon (I do this when it’s close to 10% N1). Afterward, the pilot gives the command to disarm the slides to the flight attendants. Once they disarm them and we verify in the DOOR SD, we turn off the seatbelt, and after this, they can open the doors and commence the deboarding.

I hope this helps! If you have any more questions or need further assistance, feel free to ask.

**Comment by Fragtality** [comment]
Thanks!

I don't really see this, it is not about automating every single SOP/Flow out there. 

But it at least allow different SOP/Flows to be followed. I could expand the INT/RAD Switch Thingy to call the Deboarding Service. So you could go with Auto-Deboard disabled and start Deboarding via that Switch when you want it to start.

**Comment by Fragtality** [comment]
So the Alternative is not of any Interest?

**Comment by Arsedi** [comment]
Hello, how are you?

I’m sorry, I think I accidentally closed the chat on GitHub without meaning to. Honestly, it’s my first time using GitHub.

Also, I apologize for misreading about the BEACON. Your idea is intriguing, and I could also use the PA button for that to issue commands to the GSX!

Greetings!

Enviado desde mi iPhone

El 4/09/2023, a la(s) 12:49, Fragtality ***@***.***> escribió:

﻿

So the Alternative is not of any Interest?

**Comment by Fragtality** [comment]
Sorry, I can't follow ?

The Tool is already waiting for the Beacon to be off (after Engines off and Parking Brake set) before the Jetway/Stairs are called. And only when they have finished connecting the Deboarding (if enabled) will be called.

What do mean you with PA Button? That is not what I wrote (neither something else with the Beacon)

**Comment by Fragtality** [comment]
So what is the Deal now?

**Comment by Fragtality** [comment]
Deactivate Automatic Deboarding and initiate Deboarding through the INT/RAD Switch when you feel it is right. Should now work with Version [0.3.2](https://github.com/Fragtality/Fenix2GSX/releases/tag/v0.3.2) !
