### ISSUE TITLE
Passengers not loading

### ISSUE THREAD

**Issue by fearlessfrog** [Fragtality/Fenix2GSX#42]
Everything seems to work apart from passengers not showing as incrementing on the EFB in the Fenix. When the loading sheet comes in it has zero passengers. GSX shows them walking on. Fueling, catering, cargo all works ok.

Fenix2GSX v0.3.2
MobiFlightWASM 0.7.1
GSX Pro 2.7.2

Up to date simbrief plan. GSX simbrief ignore time set.
Boarding density 'Very Dense', but happens on Normal density as well.
Tried setting ignorePaxSafeguard to true in .config but no change.

Settings
![image](https://github.com/Fragtality/Fenix2GSX/assets/15897268/99748cac-73c1-48d1-a886-e738c187135b)

GSX 1
![image](https://github.com/Fragtality/Fenix2GSX/assets/15897268/b0897771-79f5-42b9-8d72-6cc35831dcc6)

GSX 2
![image](https://github.com/Fragtality/Fenix2GSX/assets/15897268/22f07dac-9cac-47d2-a310-cfac63c88a4c)

Log 
[fenix2log.txt](https://github.com/Fragtality/Fenix2GSX/files/12553927/fenix2log.txt)

**Comment by fearlessfrog** [comment]
> When the loading sheet comes in it has zero passengers.

Yep, when the final LS comes in the weights and CG are incorrect, as it show 0 + 6 (no passengers at all and just the crew). So it's like on the Fenix side the passengers are not getting added.

Is there more info in the verbose log, as I could try that?

**Comment by fearlessfrog** [comment]
I uninstalled the Fenix and reinstalled v1.5.2.214 (I hadn't updated in a while) and that seems to have solved this, as all working well now. This issue can be closed, and I guess the reason was 'Old version of Fenix, update your aircraft!' :). Thanks for this doing this util and making it available, love it. 👍

**Comment by Fragtality** [comment]
Uhm - you had still "V1" installed?! You must be an Unicorn 😅 

Yeah the Tool needed an Update with V2B1 since the Passenger Count was increased to 180. So Fenix2GSX in the End send something the old Version could not understand :wink:
