### ISSUE TITLE
Simconnect not working

### ISSUE THREAD

**Issue by Bokepacha** [Fragtality/Fenix2GSX#47]
Hello!

I only used your program once on the previous version (0.3.2 maybe?) and it worked like a charm. I installed today 0.3.3 from scratch (deleting the old version) and it's only detecting the SIM, but nothing else.

I decided to reinstall everything from scratch (your program, the WASM module and the .NET7 libraries (restarting the PC after it). The WASM module's .json file follows the expetec path of _Community\mobiflight-event-module\layout.json._

GSX is on the latest version (updated today)

Debug.log says nothing to me.
[debug.log](https://github.com/Fragtality/Fenix2GSX/files/12671643/debug.log)

Ad this is how the program looks all the time
![Fenix2GSX_OutteqWwoY](https://github.com/Fragtality/Fenix2GSX/assets/145554868/bcd5cc75-5fa5-451e-8707-8f703fa05ba3)

I am probably missing something silly, but for the love of god I can't see it :)

EDIT: I launch the program via FSUIPC, but I didn't add any info on that as the program launches correctly.

**Comment by Fragtality** [comment]
Hmm, that is interesting. It do acknowledges the Ping but does not get a Connection. That's new.

- I would need the Logs called Fenix2GSX<date>.log
- What happens if you start the Program manually when MSFS is in the Main Menu? (Although it should be fine through FSUIPC when implemented like shown in the Readme)
- Maybe I overlooked something silly: what Happens if you use the Captain Seat Position

**Comment by Bokepacha** [comment]
[Fenix2GSX20230920.log](https://github.com/Fragtality/Fenix2GSX/files/12673005/Fenix2GSX20230920.log)
I hope this is the correct log you request.

I have started the program manually too, before starting the sim. There is no different behavior.

Captain position is where it sits by default. I just switched it to first officer right before the screenshot.

**Comment by Fragtality** [comment]
> I hope this is the correct log you request.
Yep :)

> I have started the program manually too, before starting the sim. There is no different behavior.

No different Behaviour as in "there is no different Behaviour when starting it manually in the Main Menu"?

> Captain position is where it sits by default. I just switched it to first officer right before the screenshot.

So you mean you had the same Messages with the Captain Position?


ONE Question: what did you do with you old .config File?

**Comment by Bokepacha** [comment]
I am testing the previous version 0.3.2 and I see the same issue arising.

![image](https://github.com/Fragtality/Fenix2GSX/assets/145554868/e2b12c2c-5fe1-4364-a96f-34f22f6de434)


[debug.log](https://github.com/Fragtality/Fenix2GSX/files/12673165/debug.log)


> No different Behaviour as in "there is no different Behaviour when starting it manually in the Main Menu"?

Correct, the program presents the same issues and same behavior trying to connect.

> So you mean you had the same Messages with the Captain Position?
Yes, you can see it in the new picture
 
> ONE Question: what did you do with you old .config File?

Delete it.

**Comment by Fragtality** [comment]
Strange Indeed!

The Logs don't really give a Clue sadly:
- Please send me your .config File
- Please enable Verbose Logging (loglevel in the .config to "Verbose"), start Fenix2GSX again and retry

**Comment by Fragtality** [comment]
And which Version of the WASM Module are you using? 0.7.1?

**Comment by Bokepacha** [comment]
0.7.1 indeed. I reinstalled everything today from scratch

Where is the config file? I can't find anything in the folder with a search of *config*, apart from 3  json files.

**Comment by Fragtality** [comment]
It is the File
`Fenix2GSX.dll.config`

(If your Windows Explorer is set to the Default of not showing File Extensions, it would be Fenix2GSX.dll I guess)

**Comment by Bokepacha** [comment]
Maybe this is the one?
[Fenix2GSX.dll.config.txt](https://github.com/Fragtality/Fenix2GSX/files/12674082/Fenix2GSX.dll.config.txt)

**Comment by Fragtality** [comment]
Yes-No 😅 

Yes that is the File: but where did the .txt Ending come from? And it seems that is the File from 0.3.2 right?

**Comment by Bokepacha** [comment]
I added the .txt otherwise I was not able to upload it. Github was not allowing me to.

**Comment by Fragtality** [comment]
Ahh! Alrighty! 👍

**Comment by Bokepacha** [comment]
Oh well...I reinstalled 0.3.3 and now it works :/ hahaha

![image](https://github.com/Fragtality/Fenix2GSX/assets/145554868/c6a8add4-0173-4645-8d25-23f560dfad0b)

**Comment by Fragtality** [comment]
Uhm - okay!? Apparently must have been Gremlins or something 😅 
Let's hope it stays that Way! 👍
