### ISSUE TITLE
Passenger number jumping

### ISSUE THREAD

**Issue by HaDeSMonsta** [Fragtality/Fenix2GSX#48]
As seen in [this video](https://youtu.be/do22M1pLrFM) the passenger number jumps when using Fenix2GSX.

**Comment by Fragtality** [comment]
Yeah, I watched it when you posted it in the Fenix Discord.

Like I already said there: Was that with 0.3.3? Where are the Logs of that Situation? 😉

**Comment by Fragtality** [comment]
@HaDeSMonsta 
Logs wen?

**Comment by Fragtality** [comment]
@HaDeSMonsta
Logs wen?

Last Chance. Like I said: I can only Fix what I can analyze.

**Comment by TootY1993** [comment]
I had something similar, where are the logs kept and I will send them over.

**Comment by Fragtality** [comment]
Please don't use EFB and GSX Boarding at the same Time. It is as simple as that.

**Comment by TootY1993** [comment]
I didn't..

**Comment by Fragtality** [comment]
Then the Fenix2GSX<date>.log please. In the Folder where you put Fenix2GSX.

**Comment by TootY1993** [comment]
[Fenix2GSX20230924.log](https://github.com/Fragtality/Fenix2GSX/files/12709271/Fenix2GSX20230924.log)

**Comment by Fragtality** [comment]
Time it happened?

**Comment by TootY1993** [comment]
Around 18:00

**Comment by Fragtality** [comment]
The Session you have ended with never disabling the Beacon or the Session you have started then?

**Comment by Fragtality** [comment]
Ohhh ... you mean the Jumps from 0 to 60?

**Comment by TootY1993** [comment]
> Ohhh ... you mean the Jumps from 0 to 60?

Yes, regarding the jumps in loading passengers. Loaded them within a few seconds

**Comment by TootY1993** [comment]
Completed 2 flights before this without a problem, just seemed to be this 3rd flight

**Comment by Fragtality** [comment]
From the Release Notes
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/24838304-69f2-4932-a5f2-fbb6560fd251)

Also, there is something wrong with your GSX Installation or the Way using it. I see things like 'All S Parking positions' or 'Request FollowMe?' when the Operator Question could appear. That is certainly not normal.

**Comment by TootY1993** [comment]
It's only happened since I updated GSX today and redownloaded Fenix2GSX. Before this change, I have never had this.
Furthermore, I do not use GSX window at all and allow your application to control everything. I only load the flight plan in via the EFB.

**Comment by Fragtality** [comment]
Well, that is the Way it is with/after 0.3.3 - because the Alternative with older Versions would have been that you only got 10 Passengers board (because the two 60 Pax at once would have been ignored).
In either Case: something is misbehaving in your Setup. Either SimConnect is overloaded or GSX is corrupted.
See: https://github.com/Fragtality/Fenix2GSX#refuel-stops--problems-with-boarding-or-deboarding--other-erratic-behavior

You need to use the Menu. Fenix2GSX does *not* control everything. Which is also something I have written.

**Comment by arpal-jpg** [comment]
Hello.  I have the same problem.  14 pax boarding normally in the beginning and then nothing happens neither on the EFB nor visually until boarding is completed and i get a final loadsheet.  I tried your guide and found out that i have the problem only when connected to vatsim.  I attach you the log file, the two final boarding attempts where online and offline respectively.  How can i fix this when being online?
[Fenix2GSX20231009_001.log](https://github.com/Fragtality/Fenix2GSX/files/12844837/Fenix2GSX20231009_001.log)
