### ISSUE TITLE
Custom audio for simulator

### ISSUE THREAD

**Issue by sushiat** [Fragtality/Fenix2GSX#49]
Hi, I would like to assign the sim itself to one of the audio knobs (vhf1 and int work perfect).

So I added CAB=FlightSimulator (also tried VHF3) and I can see a log message that it found an audio session for it, but the volume isn't changing. Manually adjusting the sim in the volume mixer of windows does work.

Is that something you encountered?

**Comment by Fragtality** [comment]
Nope, I use that myself all the Time (also on CAB).
So probably something with your System/Configuration.

You are aware that the Audio-Control Features only work on one ACP (corresponding to the selected Seat Position)?

**Comment by sushiat** [comment]
Yes, only ever used the captain's side. Will try again on my next flight.
Not sure if it works changing it mid-session.

**Comment by Fragtality** [comment]
I could only imagine that MSFS somehow opened another Audio-Session on a different Audio-Device. Fenix2GSX will use the first Session it finds.
Maybe something with the MSFS ATC?

**Comment by sushiat** [comment]
Don't use the sim ATC, was flying on vatsim at the time. I will try it out
this evening and report back. And I checked in task manager, there was only
one flightsimulator.exe running as I was wondering about the multi session
thing too.

**Comment by Fragtality** [comment]
One Program/Binary can have multiple **Audio**-Sessions regardless if you actively use it ...

**Comment by sushiat** [comment]
Gotcha, so maybe iterate over them and adjust the volume of all, just in
case
