### ISSUE TITLE
Volume Control still working even when disabled

### ISSUE THREAD

**Issue by Fragtality** [Fragtality/Fenix2GSX#5]
Well the fuel bug seems to have been fixed, but I think there's a new issue now. I have GSX audio control disabled, but my VHF1 is sticking to 118.100, even if I disable all options related to audio, it keeps automatically changing it to 118.100, and the volume control on the knob still works even if I disable it.

_Originally posted by @Berzerker in https://github.com/Fragtality/Fenix2GSX/issues/4#issuecomment-1528165606_

**Comment by Berzerker** [comment]
I just tried it not 10 minutes ago and it was working fine. Perhaps the sim needed a restart as well? I'll test it with a lbs configured aircraft too, to see if it's still not working, but the option was enabled when I first started it up with the sim.

**Comment by Fragtality** [comment]
Fuel is closed, please don't mix Issues.

I hardly can believe that your Frequency Issue has anything to do with Fenix2GSX - it does not even read the Frequencies or the Frequency-Knob (why should it).

What exactly do you mean with "the volume control on the knob still works even if I disable it"?
I would need you .config and the Log from the Time when that happened and the exact Steps/Order. What was when started, what was when changed.
It should handle most Cases and saw no Problems when testing, but maybe I've overlooked a special Corner-Case.

**Comment by Berzerker** [comment]
> Fuel is closed, please don't mix Issues.

I'm aware but I don't know if that perhaps had something to do with it since the a/c I'm in now is configured for kg instead of lbs where it wasn't working last night, which is why I mentioned I'll test it.

> I hardly can believe that your Frequency Issue has anything to do with Fenix2GSX - it does not even read the Frequencies or the Frequency-Knob (why should it).

> What exactly do you mean with "the volume control on the knob still works even if I disable it"?

The control for the knob, changing the volume of vpilot, for ex, worked even if the option was disabled. I unchecked the box, the log confirmed the option was turned off, but the mute and volume functions still worked to control vpilot as if it was enabled.

Like I said, maybe a sim restart was also required after changing the option, but I didn't change anything in the sim or PC except upgrading to 0.2.9.

**Comment by Fragtality** [comment]
> I'm aware but I don't know if that perhaps had something to do with it since the a/c I'm in now is configured for kg instead of lbs where it wasn't working last night, which is why I mentioned I'll test it.

If there is really still an Issue with the Fuel, please use the initial Report! I've reopened there so you can post your findings there :)

> The control for the knob, changing the volume of vpilot, for ex, worked even if the option was disabled. I unchecked the box, the log confirmed the option was turned off, but the mute and volume functions still worked to control vpilot as if it was enabled.

There are two Knobs monitored - that is INT for GSX and VHF1 for any App configured by the User. Disabling the Check-Box for GSX will only disable GSX Volume Control.
Disabling the Volume Control for the VHF1-App is done by entering nothing in the Textbox (so that it is empty).

> Like I said, maybe a sim restart was also required after changing the option, but I didn't change anything in the sim or PC except upgrading to 0.2.9.

Hmm, restarting the Sim should not be required. Also restarting the App - the Improvements in 0.2.9 where all targeted that any Option can changed on the Fly (except waitForConnect ... but I'm thinking of removing that from the GUI anyway)

**Comment by Fragtality** [comment]
Version 0.3.0 is out, you can try if that makes any difference for you.
When I receive no further Feedback or Information in the next 24 Hours, I'll close this Issue.

**Comment by Berzerker** [comment]
Sorry for not updating. I did another flight and it seemed to work ok. If I have any issues after upgrading to 0.3.0, I'll re-open one of them. You can close both for now. 

Thank you for the help!

**Comment by Fragtality** [comment]
No problem, you're welcome - Feedback is appreciated! :) 
It is just that I need some Infos to really look into something ^^

So if there should be any Issues, I need a detailed report (including Log) on what when where. I did a ~6 Hour Long Session with 4 Flights in total and it "just worked".
