### ISSUE TITLE
Turn-Around refueling

### ISSUE THREAD

**Issue by alpet666** [Fragtality/Fenix2GSX#50]
I had an interesting bug yesterday when did a turn-around at LTFM - the app said "Catering is requested" and "Refuel is requested" but only catering trucks came - fuel truck did not come... So, catering was done, I waited a few more minutes just to be sure the fuel trucks was still not coming  (GSX did not show "fuel truck is coming" too), then asked via GSX - the truck appeared shortly, and the app said "Refueling in progress"
[Fenix2GSX20230924.log](https://github.com/Fragtality/Fenix2GSX/files/12717787/Fenix2GSX20230924.log)

**Comment by Fragtality** [comment]
When Fenix2GSX calls it and GSX does not send it - how is that my Problem?
