### ISSUE TITLE
refueling and boarding.

### ISSUE THREAD

**Issue by ashun99** [Fragtality/Fenix2GSX#52]
When refuelling is going on and if I manually request boarding, suddenly  tanks are filled to designated quantity and refuelling is completed. I tried with and without ticking option for boarding after refuelling. It is the same.

**Comment by Fragtality** [comment]
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/7e560fbd-b0d5-47c6-a013-eaae2f597f28)
