### ISSUE TITLE
Plane not fully loaded

### ISSUE THREAD

**Issue by jcalor** [Fragtality/Fenix2GSX#53]
Hey. I've just noticed that boarding and cargo are completed but there's less boarded passengers and loaded cargo than planned:

![image](https://github.com/Fragtality/Fenix2GSX/assets/61759243/7c680b0b-6b22-465d-af89-a75197f3eaa0)

Log attached.
[Fenix2GSX20231030.log](https://github.com/Fragtality/Fenix2GSX/files/13206780/Fenix2GSX20231030.log)

**Comment by Fragtality** [comment]
Working as designed.
Read the Tooltips in the GUI / the Readme ;)
