### ISSUE TITLE
fenix2gsx not working

### ISSUE THREAD

**Issue by unofficialnakul** [Fragtality/Fenix2GSX#54]
hi team, i start the fenix2gsx then start smfs load aircraft at the airport. start the fenix a320 then import simbrief plan from efb. nothing happens. have to manually req fuel etc. it used to work fine but not nothing works. have uninstalled and reinstalled the app. but no luck. secondly before the update it used to work but have to manually req for boarding rest worked fine. pls see to it
cheers

**Comment by Fragtality** [comment]
I've looked into my magical Crystal Ball and unfortunately it did not know what your Problem is.

Note the Support Policy:
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/66fe77de-7df3-437f-8112-2e83826333de)

**Comment by Fragtality** [comment]
Still no Logs => closing

**Comment by unofficialnakul** [comment]
[Fenix2GSX20231110.log](https://github.com/Fragtality/Fenix2GSX/files/13312781/Fenix2GSX20231110.log)
Here's the log file. still no luck. sorry for the delay

**Comment by Fragtality** [comment]
Fenix2GSX does not even detect your Sim is running (in the Logs you send).
Don't know what is causing this. Did you rename the Binary of MSFS somehow? Do you run either MSFS or Fenix2GSX as Admin?

**Comment by unofficialnakul** [comment]
[Fenix2GSX20231110_006.log](https://github.com/Fragtality/Fenix2GSX/files/13322969/Fenix2GSX20231110_006.log)
[Fenix2GSX20231110_007.log](https://github.com/Fragtality/Fenix2GSX/files/13322970/Fenix2GSX20231110_007.log)
[Fenix2GSX20231111.log](https://github.com/Fragtality/Fenix2GSX/files/13322971/Fenix2GSX20231111.log)

here some more latest log files.

**Comment by Fragtality** [comment]
Your Logs are totally strange. First GSX is not detected as running most of the Time ("Couatl Engine not running") and then you're starting on a Runway with a Flight-Phase shorter than 5 Minutes without an Importing a Flight Plan at any Time.
Besides that the first two logs are Split in two Files with overlapping Time Stamps. As if two Sessions of Fenix2GSX run in parallel.

I never seen such immense Issues, that I can hardly believe that "Fenix2GSX not working" can be your only Issue in your Setup. It's like SimConnect is totally broken down 99,9999999% of the Time.
Sorry, but I can not see how I can help here. If it really was working before, you did something else to make it that bad. I can not really believe everything was totally fine and then you just updated Fenix2GSX and had that Result.

**Comment by unofficialnakul** [comment]
May be bcz I was practicing landing with fsipanel! Will conduct one full flight again and resend the logs! I uninstalled gsx entirely and fsdt installer as well! Maybe it helps! Sent from my iPhoneOn 11-Nov-2023, at 04:45, Fragtality ***@***.***> wrote:﻿
Your Logs are totally strange. First GSX is not detected as running most of the Time ("Couatl Engine not running") and then you're starting on a Runway with a Flight-Phase shorter than 5 Minutes without an Importing a Flight Plan at any Time.
Besides that the first two logs are Split in two Files with overlapping Time Stamps. As if two Sessions of Fenix2GSX run in parallel.
I never seen such immense Issues, that I can hardly believe that "Fenix2GSX not working" can be your only Issue in your Setup. It's like SimConnect is totally broken down 99,9999999% of the Time.
Sorry, but I can not see how I can help here. If it really was working before, you did something else to make it that bad. I can not really believe everything was totally fine and then you just updated Fenix2GSX and had that Result.

**Comment by unofficialnakul** [comment]
Hi, 
I think I found what is making my couatl to not run! It’s avast antivirus! When I disabled it fenix2gsx runs like before! I also made exceptions in avast for couatl.exe(maybe it’s couatl.xml)and addons manager folder but still it doesn’t run! But after disabling antivirus things run again! Any solution to it? Anymore files to keep in exceptions? M 100% sure it’s the antivirus which is doing something with either gsx or fenix2gsx! Hope u will guide me to make things simpler and smoother. Waiting for hearing from you! Can’t wait to fly with fenix2gsx again!
Thanx for the support!
Cheers
Sent from my iPhone

**Comment by Fragtality** [comment]
Well, typical RTFM Error.
Both the Readme of Fenix2GSX and GSX recommend to set Exclusion in the AV Software. Both recommend to exclude the whole Folder.

Please understand that I can't provide basic PC/Software Usage Support here.
But since I happen to use avast too:
- It is "Exceptions" Entry in the Settings (not the blocked/allow Apps)
- I always add "\*" to an excluded Folder
- When flying I disable avast completely (until the next Reboot)

That's all I can give you.
