### ISSUE TITLE
Volume control not working

### ISSUE THREAD

**Issue by jcalor** [Fragtality/Fenix2GSX#59]
I have set up PilotUI as Custom App to control its volume (it's IVAO Altitude Pilot client). It's recognized correctly by Fenix2GSX (see logs), but when I turn the knob or push/pull, nothing happens.

![image](https://github.com/Fragtality/Fenix2GSX/assets/61759243/ede770e8-eb2e-4aa5-8d5d-ff36a0b048cd)

**Comment by Fragtality** [comment]
There are no Logs attached.
