### ISSUE TITLE
Fenix2GSX won't open when sim is open

### ISSUE THREAD

**Issue by Harry-Edwards** [Fragtality/Fenix2GSX#60]
Hi,

I can't seem to open fenix2GX whenever the sim is open, I open it, it appears in the system tray for a few seconds, then disappears, when checking task manager it isn't open and nothing happens in the sim. 

Any ideas?

Thanks!

**Comment by Fragtality** [comment]
No.

Any Logs?

**Comment by Harry-Edwards** [comment]
Here's the logs. That's all it gets up to. This use to work in version 0.36. 
[Fenix2GSX20240102_004.log](https://github.com/Fragtality/Fenix2GSX/files/13812258/Fenix2GSX20240102_004.log)

**Comment by Fragtality** [comment]
Don't know what is messed up, the Filename of the Log should not be like that in the first Place.

Fiddled with "run as admin" on anything?
Forgot to edit the AV-Exclusion to the new Install Location?
Attempting to start multiple Instances (i.e. setup Auto-Start in both FSUIPC in MSFS)?

**Comment by Harry-Edwards** [comment]
I'll add an exclusion to it and see if that does it. However, running it before the sim starts seems to work. I've tried it with MSFS, but not FSUIPC. I will try.

**Comment by Fragtality** [comment]
So you've ignored what the Installer told you. Maybe there are other Things you've missed and I've already written down ... ?

Watch out - the Installer does not remove any Entries in the other (not selected) Auto-Start Option. Remove the Entry for Fenix2GSX yourself, before setting up Auto-Start via FSUIPC

**Comment by Harry-Edwards** [comment]
Ok so a re-install and a manual download of the requirements has fixed it.

**Comment by paulwain** [comment]
I'm also having this issue, It seems work but I cant access the menu from the system tray as it disappears when on the home screen when MFS starts up.
