### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by paulwain** [Fragtality/Fenix2GSX#61]
Hi, 

Is anyone else having issues with it working?  Have been using it for months so not new to the program. 

I have latest version, and have updated FSUIPC. When I load MFS, it seems to load up with FSUIPC as normal and then when on the home screen on MFS it disappears. I tried to run it again but it then doesn't work. 

Any suggestions? I tried deleting the folder and reinstalling it, removed the entry from the FSUIPC file and run the installer again but same issue.

**Comment by Fragtality** [comment]
So where are your Logs then :P

To rule out the very Basics (I have to): You are aware that Windows hides Icons in the Systemtray after a while? So when you click on that Arrow-Up 
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/f98375cf-35c7-4a01-9301-1a8bbc07b56a)
the Icon is also not visible anymore?

Btw please continue in this Issue, since it cant be the same as in #60.

You already checked the [Troubleshooting-Section](https://github.com/Fragtality/Fenix2GSX#does-not-start), right?

**Comment by paulwain** [comment]
Thank you replying - yes I know how to use the system tray / the program as I have been using it for months lol 

Today I only updated the software and updated FSUIPC so not sure what's happened as its not my first time doing so.

So I have set Fenix2gsx to auto start with FSUIPC, It application starts when loading the sim (Icon is in the system tray) but when on the home screen the icon disappears from the system tray so I don't have access to menu. 

When sim is loaded and in the cockpit - I hear the ding ding sounds - and it seems to work fine - A/C positions itself, jetway attaches etc etc -Import plan from the EFB - Fuel and catering trucks arrive etc etc .  

I have looked into the troubleshooting - I checked I am running the correct NET Runtime 7.0 , I installed manually again the mobiflight-event-module - and checked its showing in Community folder. I have also checked the FSUIPC folder and the correct entry is showing.  I can try and reinstall NET runtime but away from computer right now. 

Here are the logs. 

[Fenix2GSX20240104.log](https://github.com/Fragtality/Fenix2GSX/files/13831993/Fenix2GSX20240104.log)
[Fenix2GSX20240104_001.log](https://github.com/Fragtality/Fenix2GSX/files/13831994/Fenix2GSX20240104_001.log)

**Comment by Fragtality** [comment]
Hmm interesting. It is somewhat similiar to #60 - those split Logs aren't a good Sign (_001.log and so on). There should only be one Log-File per Day (for the last 3 Days).

Can you check your EXE.xml if there is also an Entry for Fenix2GSX?
You have edited the Exclusion in the AV Software for the new Path? (everything under %appdata%\Fenix2GSX)

**Comment by Fragtality** [comment]
Also: Please Monitor the Situation with the Task Manager (Details Tab).
Confirm if Fenix2GSX is not running before starting MSFS and then start it. Does the Fenix2GSX Binary completely disappear when the Tray Icon disappears?

**Comment by paulwain** [comment]
> Hmm interesting. It is somewhat similiar to #60 - those split Logs aren't a good Sign (_001.log and so on). There should only be one Log-File per Day (for the last 3 Days).
> 
> Can you check your EXE.xml if there is also an Entry for Fenix2GSX? You have edited the Exclusion in the AV Software for the new Path? (everything under %appdata%\Fenix2GSX)

Yes its added to the exlusion list, I have just checked the folder to make sure. 

What folder do I need to check the EXE ? Fenix2gsx ? Fsuipc? 




> Also: Please Monitor the Situation with the Task Manager (Details Tab). Confirm if Fenix2GSX is not running before starting MSFS and then start it. Does the Fenix2GSX Binary completely disappear when the Tray Icon disappears?


I have just done some testing: 
I restarted computer, checked task manager Fenix2gsx is not running 
Started MFS - FSUIPC starts then FenixGSX2 loads - Shows in Task Manager)
On home screen - Icon disappears - but remains in task manager ( I guess this explains why it still works when In cockpit)

HOWEVER - I just tried something, when the Icon appears on start-up, If I open the menu and keep it open from that point, it remains open for the flight - If I close off the window, it then disappears from the system tray and cant get it back.. Weird eh? 

I have also tried reverting back to 3.6 version - Menu stays open on that version fine....

![IMG_5339](https://github.com/Fragtality/Fenix2GSX/assets/155645900/9ed8bdac-af26-4708-a051-7b690c132f8b)

**Comment by Fragtality** [comment]
> What folder do I need to check the EXE ? Fenix2gsx ? Fsuipc?

It is either
`USERFOLDER\Appdata\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\EXE.xml` (MS-Store)
`USERFOLDER\AppData\Roaming\Microsoft Flight Simulator\EXE.xml`

> I have just done some testing:
I restarted computer, checked task manager Fenix2gsx is not running
Started MFS - FSUIPC starts then FenixGSX2 loads - Shows in Task Manager)
On home screen - Icon disappears - but remains in task manager ( I guess this explains why it still works when In cockpit)

> HOWEVER - I just tried something, when the Icon appears on start-up, If I open the menu and keep it open from that point, it remains open for the flight - If I close off the window, it then disappears from the system tray and cant get it back.. Weird eh?

And what would happen if you don't keep the Window open. Would Fenix2GSX do also do its Service Calls without TrayIcon (it should)? Important would be: is the Final Loadsheet transmitted also after Boarding?

**Comment by paulwain** [comment]
> > What folder do I need to check the EXE ? Fenix2gsx ? Fsuipc?
> 
> It is either `USERFOLDER\Appdata\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\EXE.xml` (MS-Store) `USERFOLDER\AppData\Roaming\Microsoft Flight Simulator\EXE.xml`

 I have just checked, and the entry is there, I have attached a picture.

> > HOWEVER - I just tried something, when the Icon appears on start-up, If I open the menu and keep it open from that point, it remains open for the flight - If I close off the window, it then disappears from the system tray and cant get it back.. Weird eh?
> 
> And what would happen if you don't keep the Window open. Would Fenix2GSX do also do its Service Calls without TrayIcon (it should)? Important would be: is the Final Loadsheet transmitted also after Boarding?

Just did another quick test, all services work without the tray icon and final load sheet received when boarding is complete, and in task manager application is still running.

I mean the app is still working for me, so I cant complain, Its just a piece of software that I cant use without anymore lol. I can change the settings before the sim loads and then just leave it from there so its not a massive biggy - and if no one is reporting anything it might be something on my side i've done :/ 


Another 2 logs for your info.
[Fenix2GSX20240105.log](https://github.com/Fragtality/Fenix2GSX/files/13841495/Fenix2GSX20240105.log)
[Fenix2GSX20240105_001.log](https://github.com/Fragtality/Fenix2GSX/files/13841496/Fenix2GSX20240105_001.log)
![IMG_5340 (1)](https://github.com/Fragtality/Fenix2GSX/assets/155645900/b0a6697c-54f4-4772-b971-e5a03b370fa9)

**Comment by paulwain** [comment]
> > I have just checked, and the entry is there, I have attached a picture.
> 
> Please remove either the Entry in the EXE.xml (or changed its Disabled Value to True). What happens then?

HORRAYYY!! Its worked. I removed the entry from the EXE.xml file - started the sim app and icon is back to normal and can access the menu in flight.

Thank you for your patience and helping me. :)

**Comment by Fragtality** [comment]
Ah alright :)

Maybe I should add some Code to protect Users from theirself 😅
