### ISSUE TITLE
Push-Back was skipped

### ISSUE THREAD

**Issue by demullewie** [Fragtality/Fenix2GSX#62]
After "Final loadsheet sent via ACARS", Parking Break ON, Ext Power OFF, Beacon OFF I request push-back via GSX Menu.
Nothing happens.
Fenix2GSX log file : "Push-back was skipped (GSX Service 6 / AC on Ground : True)" + "State change : Departure -> Taxi-Out"
And nothing happens....

**Comment by Fragtality** [comment]
Nothing? So not even the Ground-Equip was removed?

Are you sure Pushback was not disabled at that Spot/Gate? Sounds like a Taxi-Out Stand!

**Comment by demullewie** [comment]
Ground equipment was removed as soon as beacon was on.
Push-back not disabled at the gate

**Comment by Fragtality** [comment]
Alright, strange.
Nothing more I can do here with the Information provided.

**Comment by demullewie** [comment]
I tried on another airport : same issue
<img width="733" alt="image" src="https://github.com/Fragtality/Fenix2GSX/assets/76817249/602c5b50-808e-4538-8702-c166cb6b42e2">

**Comment by Fragtality** [comment]
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/112f45c7-b0e1-4a4c-99a2-7ef88a976cfe)
