### ISSUE TITLE
Boarding/Deboarding and Refueling not starting in the plane

### ISSUE THREAD

**Issue by DomWin02** [Fragtality/Fenix2GSX#64]
Hey there!

GSX is starting the Procedure but the Fenix not syncronized... So no Boarding/Deboarding or refuling by initiation the action via fenix

**Comment by Fragtality** [comment]
From Readme
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/0b2564d4-e640-45a5-a31f-f76db8022c08)

I'll give you a second Chance. Offer ends 0000Z.

**Comment by Fragtality** [comment]
No useful Information provided => Closed
