### ISSUE TITLE
Feature Request: F2GSX Relaunch on Couatl Crash

### ISSUE THREAD

**Issue by gerardojro** [Fragtality/Fenix2GSX#67]
4/6 times I have Couatl issues when I load into the sim. This has been something going on forever. It would be great if Fenix2GSX could detect a Couatl crash and kill the Couatl process while restarting it. I've tried the "Restart app + GSX" but it doesn't actually kill the Couatl process and restart it.

Just a simple feature request. It can also be a pop-up if desired. Would be extremely helpful.

**Comment by Fragtality** [comment]
No, sorry. Literally the second Requirement is "A properly working GSX Installation".
On top of that GSX has a Crash-Detection, with a Pop-Up, offering to start it again.

Restarting GSX is done via the (virtual) Menu, so it is expected that Fenix2GSX can't restart GSX when it crashed that badly.
