### ISSUE TITLE
Door re-opening after beacon is on

### ISSUE THREAD

**Issue by Berzerker** [Fragtality/Fenix2GSX#7]
Maybe I'm doing this in the wrong order or something, but I notice GSX will properly close the door, but when I go to turn on the Beacon light after the APU is avail (GPU disconnected) the door will reopen itself.

Let me know how you'd like me to test.

**Comment by Fragtality** [comment]
Fenix2GSX does not open any Door anytime - so there is nothing that needs testing from my Side.
It only close-closes the Main-Door (L1) after the Final LS was received.

Maybe re-read the Readme, especially Configuration and General Service Flow.

**Comment by Berzerker** [comment]
Well after everything is done, the door is open. All other equipment is removed, and I'm following the instructions as per the readme. I don't think I'm doing anything wrong.

 So, perhaps maybe the tool is closing the door too early and GSX is toggling it back open?

**Comment by Fragtality** [comment]
Why should GSX re-open the Door when Boarding has finished?

And you are sure, you have things like the Auto-Door and Auto Mode disabled?

**Comment by Berzerker** [comment]
...I'm not sure, that's why I said "perhaps" lol. My thought was it's how it knows to close the Fenix door, it uses a "toggle" on the command and since the tool is closing the door, GSX opens it back up because it only toggles, not opens.

Yes I definitely have both of those things disabled.

![image](https://github.com/Fragtality/Fenix2GSX/assets/448708/03995e64-0d1e-4152-83b2-0e4a95b646c1)

**Comment by Fragtality** [comment]
And on the GSX Side?
Auto Mode? Aircraft Profile internal?

**Comment by Berzerker** [comment]
Internal GSX Database shows only, Auto Mode is disabled per the readme.

The only thing I noticed was my time acceleration for refueling was 3x, would that have caused the issue? I set it back to 1x just now.

**Comment by Fragtality** [comment]
Any other Addons installed that could interfer? Fs2Crew, PacX  or there like could have their own Automations?

**Comment by Fragtality** [comment]
Don't know if it is, but the *Readme* recommends to leave it at 1x ...
The Refuel-Rate is configurable in the Fenix2GSX GUI

**Comment by Fragtality** [comment]
Do you trigger the Ground-Equipment-Removal after the LS has been received?

**Comment by Berzerker** [comment]
I don't have any other addons that have automations

> Do you trigger the Ground-Equipment-Removal after the LS has been received?

I honestly don't remember if I did, but I'll try it this time after the LS is received.

**Comment by Fragtality** [comment]
I think you did.
I set Parking Brake, switched Beacon on and disconnected Ext Pwr before the LS was send. The Door was instantly re-toggled open when after the LS was received.

**Comment by Berzerker** [comment]
Ok, seems like you're right. I waited for the LS and it didn't re-open the door. Perhaps some check can be put in place where the equipment can be removed and pushback can be prepared while waiting for the LS instead of requiring to wait until you receive it?

**Comment by Fragtality** [comment]
Took a while to figure it out. It is indeed GSX which is re-opening the Door. Or more precisely: it is toggling the Door because it thinks it is still open. It does check the current State of the Door (else it would have happened every time) somehow, but it seems not fast enough for that specific Situation.

Try the latest RC1 for 0.3.1 and look how it does for you! I safe-guarded the Line a bit where Fenix2GSX closes the Door (so GSX can do it) and above all I made the Final LS independent of the Ground-Equipment-Removal and Pushback-Handling. So you can depart before it is send.
I asked some Pilots and it is indeed very different between Company SOPs. Some don't allow to Push-Back before it is received. Some allow Push-Back but not Taxiing without. Some even allow Taxiing. But everyone disallows taking off without it 😅

**Comment by Berzerker** [comment]
> Try the latest RC1 for 0.3.1 and look how it does for you! I safe-guarded the Line a bit where Fenix2GSX closes the Door (so GSX can do it) and above all I made the Final LS independent of the Ground-Equipment-Removal and Pushback-Handling. So you can depart before it is send.

Excellent! I'll try it out

> I asked some Pilots and it is indeed very different between Company SOPs. Some don't allow to Push-Back before it is received. Some allow Push-Back but not Taxiing without. Some even allow Taxiing. But everyone disallows taking off without it 😅

Definitely makes sense, but I think even if it takes the full 150s, the pushback/startup procedure should take about that long or longer, so everyone should get it before taking off. 😛

**Comment by Berzerker** [comment]
No issues here, worked well! Thanks again for your help.
