### ISSUE TITLE
Fuel truck stay even if completed

### ISSUE THREAD

**Issue by DavidEGTE** [Fragtality/Fenix2GSX#70]
as title
![image](https://github.com/Fragtality/Fenix2GSX/assets/19428125/f3f131b6-9c58-4964-b085-ccb32e046988)
[Fenix2GSX20240309.log](https://github.com/Fragtality/Fenix2GSX/files/14547383/Fenix2GSX20240309.log)

**Comment by DavidEGTE** [comment]
the only way to progress on is to add manually the KG on the MCDU and it goes ahead with the services

**Comment by Fragtality** [comment]
What was the planned Fuel?
Seems the current FOB was greater than the planned FOB.

**Comment by DavidEGTE** [comment]
![image](https://github.com/Fragtality/Fenix2GSX/assets/19428125/beb0e277-8142-47be-82af-334ad83ceb03)

**Comment by Fragtality** [comment]
That was your Problem: 9575 > 8256.
You probably closed/restarted Fenix2GSX with a FOB of 9575 before and that was then reapplied on the Start of this Session.

For the mean Time don't close/restart Fenix2GSX when the Aircraft is already fueled (or make sure yourself that the current FOB is not higher than planned - by "Reset All" before OFP Import).
The next Version will only save the FOB upon Arrival after the Engines where stopped.
