### ISSUE TITLE
Disable stair to the aft door, when jetway, how?

### ISSUE THREAD

**Issue by SMN204** [Fragtality/Fenix2GSX#72]
How to configure that stairs are not operated to the aft entry door when Jetway is operated.
It is always stairs to the aft entry door - but it is not necessary and there is no such thing in reality!
![Jetway+stairs](https://github.com/Fragtality/Fenix2GSX/assets/60313040/627a6198-79c1-4c31-bc55-bba13c682d3b)

**Comment by Fragtality** [comment]
Disable the Staircases in GSX - either globally or per Airport Profile
