### ISSUE TITLE
How does it compare to V2 Block 2?

### ISSUE THREAD

**Issue by winternet-studio** [Fragtality/Fenix2GSX#76]
How does this compare to the new version V2 Block 2 which has native GSX integration? Please write something about that in the readme so we can determine whether we want/need this.

**Comment by Fragtality** [comment]
Could you give me some more Background on that?

As I see it, there are either Users who used it before and know that already and therefore continue to use it. Or there are Users who never used it before for various Reasons and I would not know why they would start with it now when there is a native Integration available.
Besides that the Introduction and the GUI Screenshots (which honestly would need an Update) already tell indirectly that there is a bit more too it.

So it sounds a bit to me to write something up most People would not read anyway 🤔

**Comment by winternet-studio** [comment]
So I presume you have upgraded to V2... but you are saying you haven't tried the native integration and therefore don't know how it compares? If so, the readme could even say just that sentence... that you don't know how this compares to the native integration. But have you not tried the new integration at all? Are you not interesting in knowing it? ...so that you can know whether it's worth to continue developing your integration and know which features you need?

**Comment by Fragtality** [comment]
What are you talking about?! oO

How does this answer my Question and would this convince me to write that up in the most Times ignored Readme?

**Comment by Fragtality** [comment]
Ah okay ... yeah that must be it 🤷‍♂️
