### ISSUE TITLE
After update to 0.4.10 problem!

### ISSUE THREAD

**Issue by SMN204** [Fragtality/Fenix2GSX#79]
After upgrading to 0.4.10 there are problems in operation (for example...automatic operation does not work).
Here is what it says in the log field
![Critical Exception during](https://github.com/Fragtality/Fenix2GSX/assets/60313040/78e8c465-4d10-414f-a5ad-8b6f31c96189)
In "debug.log".......
[0418/112858.261:WARNING:resource_util.cc(94)] Please customize CefSettings.root_cache_path for your application. Use of the default value may lead to unintended process singleton behavior.

Yesterday, with version 0.4.9 this did not happen!

**Comment by Fragtality** [comment]
See https://github.com/Fragtality/Fenix2GSX/issues/78#issuecomment-2059761297

Don't install Versions not compatible with your Fenix Version.
