### ISSUE TITLE
problem Fenix2GSX

### ISSUE THREAD

**Issue by sammekesamson** [Fragtality/Fenix2GSX#81]
![WhatsApp Image 2024-04-28 at 20 34 53](https://github.com/Fragtality/Fenix2GSX/assets/168368399/a924084f-17fa-40fa-af80-702c8b3954b5)

how can i fix this?

thank you

**Comment by Fragtality** [comment]
Version of Fenix and Fenix2GSX?

**Comment by sammekesamson** [comment]
version of Fenix is V2.0.0.392
and from Fenix2GSX 0.40.10

**Comment by Fragtality** [comment]
Downgrade Fenix2GSX to 0.4.9 - just run the Installer. (or upgrade Fenix to .407)
The Changelog is pretty clear.
