### ISSUE TITLE
Round up refuel figure to nearest 100KG

### ISSUE THREAD

**Issue by luke11brown** [Fragtality/Fenix2GSX#83]
As the refuel panel only allows selection in 100KG intervals, round up refuel figure to nearest 100KG, rather than matching OFP value.

**Comment by Fragtality** [comment]
Hmm 🤔 
Does the Fenix itself does that now right?

**Comment by luke11brown** [comment]
It seems to round up to nearest 10KG

**Comment by Fragtality** [comment]
And how are LBS handled on that Panel?

**Comment by luke11brown** [comment]
Never played with an A320 that uses freedom units myself, but I would imagine it's LBs x 1000, so it rounds to nearest 100lbs

ref: https://www.airbus.com/sites/g/files/jlcbta136/files/2021-11/Airbus-Commercial-Aircraft-AC-A320.pdf

**Comment by Fragtality** [comment]
Btw, It is always round up or what?
E.g. when the OFP says 4614 it would still be 4700?

**Comment by luke11brown** [comment]
Yes, always round up, never down

**Comment by Fragtality** [comment]
Mkay, try it out then ;)
https://www.mediafire.com/file/vqzbkkglmnszk4q/Fenix2GSX-Installer-v0.4.11.exe/file
(Yes it will still show as 0.4.10 so that the Update Notification works when it goes GA - it is a Dev-Build, so there might be Changes)

**Comment by luke11brown** [comment]
Works like a charm
![image](https://github.com/Fragtality/Fenix2GSX/assets/13762210/233f44d4-093a-4c5d-bda5-7089d697eb41)

![image](https://github.com/Fragtality/Fenix2GSX/assets/13762210/58b0861c-127c-4847-81f3-27f380ca137f)

**Comment by Fragtality** [comment]
Will be Part for the official 0.4.11 Release then - don't forget to Update when notified. There still might have been other Changes to your Dev-Build.
