### ISSUE TITLE
Refuel rate

### ISSUE THREAD

**Issue by TaRRaba** [Fragtality/Fenix2GSX#84]
Hello! I am using Fenix2GSX version 0.4.10 with Fenix Airbus A320 (v.2.0.0.407).

My issue is about refuel rate. For example, i planned 10 000 kg for a flight.

If i change refuel rate in Fenix2GSX app from default to 60 kg/s, then it refuels faster, but when it reaches my planned fuel (10 000) refueling animation doesn't stop by GSX and continues for some time. It feels like GSX refuel animation relies on it's own refuel rate settings and doesn't synchronize with Fenix2GSX refuel rate.

Is it a bug or i need to set some additional settings?

**Comment by Fragtality** [comment]
Tried that?
![image](https://github.com/Fragtality/Fenix2GSX/assets/78614902/dba19a29-0f4b-48ec-b57a-691376c34248)

**Comment by TaRRaba** [comment]
I am not able to change those settings.

![image](https://github.com/Fragtality/Fenix2GSX/assets/102470880/bd05b2a6-9fc1-4f87-81f5-8d902648bd56)

**Comment by Fragtality** [comment]
Oh yeah, sorry I forgot - Fenix is already using these new GSX Feature to set certain Options dynamically.

Then it would be time to provide a Fenix2GSX Log of such a Situation as per Support Policy ;)

What you might try is to disable Progessive Refuel when another Aircraft is loaded and then try again with the Fenix. (But maybe close and start MSFS again before that - Things can get strange with MSFS and SimConnect when switching Planes)

**Comment by Fragtality** [comment]
Could you please check: does this happen on both Fuel Trucks? So with both Underground Fuel and no Underground Fuel?

**Comment by TaRRaba** [comment]
Here are two log files, one of them from Dusseldorf to Yerevan (underground fuel), and the second one from Yerevan to Dusseldorf (no underground fuel). As you can see, in both cases after that refuel is completed and boarding started there is about 3 min gap between those operations. That's caused by GSX refueling animation that doesn't stop when planned fuel amount is reached.
[Fenix2GSX20240521.log](https://github.com/Fragtality/Fenix2GSX/files/15428047/Fenix2GSX20240521.log)
[Fenix2GSX20240522.log](https://github.com/Fragtality/Fenix2GSX/files/15428048/Fenix2GSX20240522.log)

**Comment by Fragtality** [comment]
> As i mentioned in previous post it was underground fuel from EDDF-UDYZ, and tanker from UDYZ-EDDL. In both cases, it was pretty same.

*D'OH*
Sorry I was blind 😓 
That the Delay is so noticeable long with both Truck Types when planned Fuel is even more than 10000, it reinforces my Suspicion that GSX still is doing "always refuel progressively" although it is disabled by the Fenix. 🤔 
<br/>

> I just reproduced the same scenery (same fuel amount for refueling, from 2400kg to 13200kg). After tanks filled it took 1 minute and 10 seconds for animation to finish. Maybe it's not too long if you do other preflight procedures while refueling, but the fact is that it's not working as it should.

Just wanted to make sure we talk about the same Thing/Delay - the unintended Delay. If I would consider that working as intended we would not have a Conversation anymore and I would not expose myself to the "Joy" of talking to FSDT Support 😉

**Comment by TaRRaba** [comment]
Just bumped topic on FSDT Support.

**Comment by Fragtality** [comment]
🤞 it helps when someone else reports that to! Almost seems to me it is ignored because I reported that. (I've asked that on Discord before that - and virtually answered Messages above and below mine ... )

**Comment by TaRRaba** [comment]
There is a new update (version 3.0) for GSX Pro released. Maybe FSDT added fix for that behaviour.

**Comment by Fragtality** [comment]
Oh no, why do they have to push it *NOW* - I'm currently busy with PilotsDeck 😅

**Comment by Fragtality** [comment]
It could be that after all it isn't a Problem with GSX and that it is rather working as intended:
When trying/troubleshooting something else, I lost a bit of Focus and ended up with troubleshooting this Issue here 😂 

And just to give it a try, I disabled that progressive Refuel Feature that is set by the Fenix Software. Et Voila, the Refuel Truck disconnected after the usual Delay after the Quantity stopped increasing.


So if you still had that Issue, try that build: https://www.mediafire.com/file/7z0e1kf3z4b7nit/Fenix2GSX-Installer-v0.4.16-refuel.exe/file

**Comment by Fragtality** [comment]
Solved in 0.4.16
