### ISSUE TITLE
A319 boarding resets passengers to 0

### ISSUE THREAD

**Issue by hotbso** [Fragtality/Fenix2GSX#87]
For the A319 (A321 not tested) Fenix2GSX resets passenger numbers (even planned!) to 0 after boarding is completed. Cargo + fuel is correct. 
The A320 boards as expected with exactly the same settings.

**Comment by hotbso** [comment]
Thanks, problem is solved.

**Comment by Fragtality** [comment]
Np, but check the Systray Icon for the Update Notification when the "true" release 0.4.12 is out - in case of any further Changes!
