### ISSUE TITLE
After shutdown aircraft teleports to eddm Munich

### ISSUE THREAD

**Issue by SZDPilot** [Fragtality/Fenix2GSX#89]
Hello,

thanks for developing the tool!
Unfortunally i experience the following issue after installing:
When shutting down the engines at the destination the aircraft automatically teleports to the active runway in munich. 
Even after uninstalling and installing of Fenix A319/320/321, fenix2GSX and GSX the issue remains.

Did you ever experience this? Can you suggest a solutions for this?

- MSFS latest version
- Fenix A319/320/321 latest build
- Latest Fenix2GSX
- Update GSX Trial

Thanks and regards!

**Comment by Fragtality** [comment]
Buy GSX.

From the Manual:
![image](https://github.com/user-attachments/assets/6d9e0a6d-eb71-437f-9c8c-63178a883d00)

So I can only assume that GSX teleports you back to the nearest Airport that the Trial allows.

**Comment by Fragtality** [comment]
No further Feedback => Closed
