### ISSUE TITLE
Not an Issue, only a question

### ISSUE THREAD

**Issue by FGrabi** [Fragtality/Fenix2GSX#9]
Hi,
I'm using your tool since a few days and I love it...but I'm not sure how to use it "the right" way. :-(

When I started from C&D and importet the Simbrief FP in EFB, the Refuelling is initiated (and the Catering). If the Fuel Truck is in position and the hose is connected, GSX asked to use the EFB to set the quantity - will keep it on the figueres from Simbrief. Now my question:
Did I need to press the "Load Aircraft" in EFB (This will also start "loading" the cargo and the pax) or not? Noticed, that the "loading" figures inreasing without pressing the button. Same question when GSX boarding starts - Press "Load" or not?
Is it possible to change/decrease the 90 sec between Refuel Finish and start Boarding?

Best regards
Frank

**Comment by Fragtality** [comment]
Hello Frank!

Hmm, sounds like you missed some Parts of the [Readme](https://github.com/Fragtality/Fenix2GSX/) - GSX should have never asked/prompted something like that for the Fenix. Never saw anything like that before.
Could be either something in the GSX Settings and/or you use a custom Aircraft Profile (which is not recommended). I hope GSX is up-to-date.

No, you don't need to press "Load Aircraft" in the EFB and in Fact I would not recommend to. The Aircraft is loaded by the respective GSX Service (Refuel Truck does the Fuel, Boarding does Passengers & Cargo). So it is either using GSX+Fenix2GSX or the EFB for Loading, but not both. Same goes for Deboarding/Unloading - just Dismiss the Popup in the EFB. If you want to "insta-load" via EFB for Test-Flights or something like that, you can just close Fenix2GSX and use the EFB like before.

No, the 90s are fixed when Auto Boarding is used to ensure the Fuel Truck has left its Position. The 90s start when the Fuel Amount has the reached the planned Fuel - so there is still a bit of GSX Animation going!
With Version 0.3.1 you should be able to call Boarding any Time you want even when Auto Boarding is enabled. You can also disable it and call the Boarding manually when you want to. Remember the Readme: The Loading Simulation/Synchronization through Fenix2GSX works always (as long as the Flightplan is loaded in the EFB), regardless who called the respective GSX Service. You don't need to enable/use the Automations to use this Core-Feature.

**Comment by Fragtality** [comment]
Closed => No further Feedback provided
