### ISSUE TITLE
Fenix A320 Passengers

### ISSUE THREAD

**Issue by glenmorangie007** [Fragtality/Fenix2GSX#93]
When the passengers board the aircraft at any given airport, the passenger display on the EFB keep moving from front to back all the time and the aircraft bounces back and forth - has this issue been rectified yet by any chance ?

I do have a video showing the issue but can't upload it here

Thanks

**Comment by Fragtality** [comment]
![image](https://github.com/user-attachments/assets/b3ae9ec4-b046-4935-a505-b480d9d245e4)

Also, that is not a proper Issue Report:
![image](https://github.com/user-attachments/assets/bd204415-51d2-4f80-a71c-3185633f949b)
