### ISSUE TITLE
Add function to not trigger GSX Pushback bit when beacon light turned on

### ISSUE THREAD

**Issue by SpoonyBoobah** [Fragtality/Fenix2GSX#95]
Hey,

Love the addon, but been trying to make it work with Self-Loading Cargo... a passenger immersion add-on... https://www.selfloadingcargo.com/

One of the things SLC does which is cool is it auto triggers GSX pushback but I also love Fenix2GSX to operate everything else as SLC only does trigger pushback and connect Stairs and/or Jetway manually, nothing else.

Would it be possible to add a option for Fenix2GSX when the beacon is turned on to disconnect everything else like the GPU and Cones etc. but not actually trigger Pushback as SLC will do it?

**Comment by Fragtality** [comment]
Thanks, but sorry I can't follow.

Why should it disconnect anything for you? And if you meant rather remove - what is the Problem with the current Triggers to remove Ground-Equip?
![image](https://github.com/user-attachments/assets/d6e80db8-84f0-49f1-a137-42e7d761a089)

**Comment by SpoonyBoobah** [comment]
Well I am a complete idiot... I didnt realise the functions were not dependant on each other lol... Completely ignore me then... hahaha thanks for making such a good tool o7

**Comment by Fragtality** [comment]
Thanks! 👍 

Be aware of the little "Trap" explained in the last Bullet-Point. The next Version will revert these two Settings and add a Message Box to inform/warn the user.

**Comment by SpoonyBoobah** [comment]
Yeah thats cool! Thanks for the heads up... for now because I have been spending time on getting SLC, Fenix2GSX and GSX to play nice... and finally got it working perfectly, am very happy as your tool provides more flexibility then the inbuilt GSX controls.

I have it working by tweaking settings...

SLC > Triggers the boarding, deboarding and pushback phases in GSX by itself...
Fenix2GSX > Monitors GSX and triggers all the ground crew actions, refueling, catering, stairs, jetway, GPU etc... 

Works really well... and the immersion is amazing... the only manual thing I have to do is after F2GSX connects the stairs/jetway, GPU automatically on start, wait until SLC's Ground Crew come alive and call you saying they are working on your aircraft and will be loading shortly... then I pull the flightplan on the Tablet which triggers F2GSX to call Refuel and Catering...
