### ISSUE TITLE
GSX selections - longer time to react

### ISSUE THREAD

**Issue by concordeag** [Fragtality/Fenix2GSX#97]
Hello, 
It would be nice, if the popups of GSX would stay longer, to actually make a selection. (Pushback Truck connector, Crew Boarding/Deboarding).

I don't have the general flag set in gsx, i rather would like to decide case by case if i want the pushbacktruck connected during boarding).

**Comment by Fragtality** [comment]
Nope, that won't happen:
- There is no Control over the GSX Menu Time-Out, I can't increase it. If you want to select something, then look out for it.
- With the weird Way the new Connect-Tug-while-Boarding Feature was implemented, Fenix2GSX must answer that Question. So you must do this Case-by-Case Decision in the Fenix2GSX UI before Boarding is called. FYI, there are two Feature-Requests to change/improve that Behavior in the GSX Community Discord - the more Votes the Better.
- Generally I don't have much Motivation to increase manual Selection further than already supported. The whole Point of Fenix2GSX is to minimize the Time you have to use GSX' Menu. We can talk about certain/special SOPs not being possible, but not about "I like operating the Menu".

**Comment by concordeag** [comment]
Hello @Fragtality 
Thanks for the reply. 

> There is no Control over the GSX Menu Time-Out, I can't increase it. If you want to select something, then look out for it.

If the plugin isn't running, the window with the question remains open, if the plugin is running, the window opens makes a selection and closes within 1 second. I literally can't click in that time.


Is there anything i can disable in the settings of Fenix2GSX?

**Comment by Fragtality** [comment]
Oh my ... of course the Time-Out will end when Fenix2GSX makes a Selection.
So disable the Skip-Option for "the" Question - possible for any Question except the Tug-Question as explained.

What is the "truck" on the Remote Stands? The Tug?
Then probably your Profiles are not configured correctly.

If "truck" is a Bus on a Walk-In Gate which has mixed Walk-In & Bus Service: that is just GSX. Can't workaround it and currently don't have Energy to report that Umberto only to get explained what I'm doing wrong.
