### ISSUE TITLE
Not receiving final loadsheet

### ISSUE THREAD

**Issue by LarsyDevelopment** [Fragtality/Fenix2GSX#99]
Hi,
loading is complete, i'm not receiving any loadsheet in the ACARS, and can't send it again from the EFB

![image](https://github.com/user-attachments/assets/03345a02-b315-4728-8404-d29e45ea523d)
![image](https://github.com/user-attachments/assets/3e73ee6b-df95-4a69-ab00-5a44bfc84045)
![image](https://github.com/user-attachments/assets/37391c50-6857-4a02-bdaf-f46c1077b087)

**Comment by Fragtality** [comment]
With no Information provided, the Issue will be closed.

**Comment by LarsyDevelopment** [comment]
Apparently it's a bug that if the option with after importing the flight plan automatically no loadsheet will be provided, if i disabled that option and manually clicked start loading using gsx in the fenix everything went fine.

Any solution?

**Comment by Fragtality** [comment]
No Problem-Description, No Solution.

**Comment by LarsyDevelopment** [comment]
Basically the loadsheet does not get send after full load. logs say that loadsheet is sent via acars but nothing is there. Meaning i can't calculate takeoff performance. While disabling automatic refueling fix this issue. Idk any other solution.

**Comment by Fragtality** [comment]
There are no Logs provided.

**Comment by LarsyDevelopment** [comment]
[Fenix2GSX20241229 (1).log](https://github.com/user-attachments/files/18270017/Fenix2GSX20241229.1.log)

**Comment by Fragtality** [comment]
Already answered on Discord.
